org_partitionneur:
    resource: "@OrgPartitionneurBundle/Controller"
    type:     annotation
    prefix:   /partitionneur

org_user:
    resource: "@OrgUserBundle/Controller/"
    type:     annotation
    prefix:   /

org_forma:
    resource: "@OrgFormaBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AcmeDemoBundle:Secured:login }
    
login_check:
    pattern:   /login_check
