security:
    encoders:
        Org\UserBundle\Entity\User: 
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Org\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
               
        partitionneur_login:
            pattern:  ^/partitionneur/secured/login$
            security: false

        partitionneur_secured_area:
            pattern:    ^/partitionneur/secured/
            anonymous: ~
            form_login:
                check_path: _partitionneur_security_check
                login_path: _partitionneur_login         
                default_target_path: _index
                
            logout:
                path:   _partitionneur_logout
                target: _index

    access_control:
        - { path: ^/partitionneur/secured/application, roles: ROLE_USER }
        - { path: ^/partitionneur/secured/administration, roles: ROLE_ADMIN }